export const avatarPixelPalette: Record<string, string> = {
  K: "#050507",
  H: "#1f2026",
  S: "#d86616",
  L: "#f28a2d",
  D: "#9f3508",
  W: "#ffffff",
  E: "#18181b",
  R: "#b0004d",
  M: "#4b170c",
  B: "#049ee8",
  A: "#22c7ff",
  C: "#a8d8e7",
  G: "#5e8794",
  P: "#078bd0",
  O: "#c8d1d6",
};

const rawAvatarRows = [
  ".............KKKKKKKKKKKK...........",
  "..........KKKKKKKKKKKKKKKKK.........",
  "........KKKKKKKKKKKKKKKKKKKK........",
  ".......KKKKKKKKKHHHHKKKKKKKKK.......",
  "......KKKKKKHHHHHHHHHHHKKKKKKK......",
  ".....KKKKKHHHHKKKKKHHHHHKKKKKK......",
  "....KKKKHHHKKKKKKKKKKHHHHKKKKKK.....",
  "...KKKKHHKKKKKKKKKKKKKKHHHKKKKK.....",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKKKKK....",
  "..KKKKKKKKKKKLLLSSSSSSKKKKKKKKKK....",
  "..KKKKKKKKKLLLSSSSSSSSSSKKKKKKKK....",
  ".KKKKKKKKLLSSSSSSSSSSSSSSKKKKKKKK...",
  ".KKKKKKKLLSSSSSSSSSSSSSSSSKKKKKKK...",
  ".KKKKKKLLSSSWWEEESSSWWEEESSKKKKKK...",
  ".KKKKKKLSSSSWEEESSSSWEEESSSKKKKKK...",
  ".KKKKKKLSSSSWEEESSSSWEEESSSKKKKKK...",
  ".KKKKKKSSSSSWWSSSSSSWWSSSSSKKKKKK...",
  ".KKKKKKSSSSSSSRRRRRRSSSSSSSKKKKKK...",
  "..KKKKKSSSSSSDSSSSSSDSSSSSKKKKKK....",
  "..KKKKKSSSSSSSSSMMSSSSSSSSKKKKKK....",
  "..KKKKKKSSSSSSSSSSSSSSSSSKKKKKK.....",
  "...KKKKKDDDSSSSSSSSSSDDDDKKKKK......",
  "...KKKKKKKKSSSSSSSSSSKKKKKKKK.......",
  "...KKKKKKKKKSSSSSSSSKKKKKKKK........",
  "....KKKKKKKKKKSSSSKKKKKKKKK.........",
  "....KKKKKKKKKSSSSSSKKKKKKK..........",
  "....KKKKKKK...SSSS...KKKKK..........",
  "....KKKKK.....SSSS.....KKK..........",
  ".............BBBBBB..................",
  "............AABBBBAA.................",
  "...........AABBBBBBAA................",
  "..........SSBBBBBBBBDD...............",
  ".........SSSBBBBBBBBBDD..............",
  ".........SSSBBBBBBBBBDD..............",
  "..........DDBBBBBBBBDD...............",
  "............CCCCCCCC..................",
  "............CCCCCCCC..................",
  "............CCGGGGCC..................",
  "............CCGGGGCC..................",
  "...........PPPP..PPPP.................",
  "..........PPPPP..PPPPP................",
  ".........OOOOOOOOOOOOOO...............",
];

export const avatarWidth = Math.max(...rawAvatarRows.map((row) => row.length));
export const avatarRows = rawAvatarRows.map((row) => row.padEnd(avatarWidth, "."));

